---
title: 'Applied Statistics'
---

###_By Ben Denis Shaffer_###

#About the Website:

This website is built from R Markdown documents, so for the most part you can expect to see statistical and computational methods implemented and explained using R. STATA and SAS might also be included. I will also do my best to include Linux workflow because I found that effective use of the terminal is very important for productivity, especially when talking about "Big Data". That being said, the website for the most part serves as kind of a notebook. Most of the content will be based on my graduate coursework at the University of Michigan. Additionally I have an interest in dedicating a section of the website to full analysis cases, perhaps from [Kaggle](https://www.kaggle.com/competitions) or [DrivenData](https://www.drivendata.org/).


#About Me:

Currently I am pursuing a [M.S. in Applied Statistics at the University of Michigan](https://lsa.umich.edu/stats/graduate-students/graduate-degree-programs/appliedmasterprogram.html) and expect to graduate either December 2017 or April 2018. Previously I have completed my B.A. at Boston University where I double majored in Mathematics and Economics. 

My career interests are in management consulting, project management and entrepreneurship. I am particularly interested in the domains of healthcare, education, mobile and home technology, urban informatics and security. Generally I get excited about anything where I see an opportunity to innovate and leverage data as a useful resource.

R programming is perhaps my greatest technical competency at this point. Right now I am committed to mastering Python and I am also interested in learning Julia later on. Other then that, I love to travel and try to always stay active doing sports and fitness. 


#Courses:

These are the courses based on which I am building the content of the website.

- Statistical Learning I: Regression [STATS:500](http://lsa.umich.edu/stats/graduate-students/statistics-courses.html)
This course focused mainly on the classical statistical analysis of data. That involves regression analysis, model diagnostics and  inferential statistics. Some more advanced topics included transformations, dimension reduction, regularized regression, robust regression and logistic regression. 

- Statistical Learning II: Multivariate Analysis [STATS:503]
Currently taking.

- Computational Methods & Tools [STATS:506](http://dept.stat.lsa.umich.edu/~kshedden/Courses/Stat506/)
In this course we were developing practical skills for working with data using statistical software packages including STATA, R, and SAS. The focus has been on understanding how the data is represented and used by computers when worked with in a given language. The emphasis was not of writing code that just works, but writing code that works efficiently. Some advanced topics included parallel/concurrent programming and distributed computing in Spark.

- Special Topics in Applied Statistics II: [STATS:701](http://dept.stat.lsa.umich.edu/~jerrick/courses/stat701/syllabus.html)
This course focuses on issues surrounding the handling of raw data. So of the topics included web-scraping, data cleaning, software development in R, visualization, among others.


#Contact:

email: [bdshaff@umich.edu](bdshaff@umich.edu)

