---
title: "Variable Selection"
author: "Ben Denis Shaffer"
date: "December 5, 2016"
output: html_document
---

#Introduction

Given a dataset there are often many predictor variable, not all of which should be included in a model. There are two main reasons. The one that is most offten brough up is parsimoniousness, which basically suggests that the simplest model is best. In the case of regression it's the model that explains the most variation with the least number of variables. The second reason is that you want to avoid overfitting, especially if your intention is to predict using the model. If you have the same number of predictors as observations you will have a perfect fit, but the model will be usless for either prediction or interpritation due to collinearity and inflated variances. 

Including too little of the predictors is also undesirbale becasue you do want to have a reasonable fit, and you want to avoid confounding variables. All this suggests that there has to be some optimal set of variables to select for the model. Some subset of the given or enginnered variables that will result in a most useful model for you. And, of course there are different methedologies avaliable to meet this end.


#Topics

- Stepwise Regression
- Information Criteria
- Adjusted $R^2$ and Mallows $C_p$

##Stepwise Procedure



```{r}
library(faraway)
data("teengamb")
model = lm(gamble ~ ., data = teengamb)         #Initial Full Model Fit.
which.max(summary(model)$coefficients[,4])      #1st Step: `status`.
summary(model)$coefficients[3,4]                #Has this p-value.
model = update(model, .~. - status)             #Update the model by subtracting `status`.
which.max(summary(model)$coefficients[,4])      #2nd Step: `verbal`.
summary(model)$coefficients[4,4]                #Has this p-value.
model = update(model, .~. - verbal)             #Update the model by subtracting `verbal`.
which.max(summary(model)$coefficients[,4])      #Got to the intercept so end proceedure

summary(model)

```


##Information Criteria

##Adjusted $R^2$ and Mallows $C_p$

#Conclusion
